### ISSUE TITLE
validate method not working properly

### ISSUE THREAD

**Issue by fpayer** [chilts/node-coupon-code#6]
It returns an empty string if you pass in any code that doesn't have the standard length or number of parts

**Comment by fpayer** [comment]
Looked at the source and noticed you need to pass in the same params you used to generate the code. Please update the README to reflect this as it is confusing.

**Comment by chilts** [comment]
Thanks for pointing this out. Feel free to do a PR, otherwise I'll try and get to it in the next few days.

**Comment by chilts** [comment]
Only changed the readme, so released as v0.4.4 to npm. Thanks for opening this issue.
